# Generated by Django 3.1.3 on 2021-10-19 23:00

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SketchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('cover', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('talkshit', models.TextField(blank=True, null=True)),
                ('talkshit_md', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('p_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.portfoliocategory')),
                ('s_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.sketchcategory')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PanoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='img/p', verbose_name='Panorama Image')),
                ('order', models.IntegerField(default=0)),
                ('postpanoimg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.post')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_img', models.ImageField(blank=True, null=True, upload_to='img/b', verbose_name='Blog Image')),
                ('postimg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.post')),
            ],
        ),
    ]
