# Generated by Django 3.1.2 on 2020-11-19 06:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('bg_color_a', models.BooleanField()),
                ('bg_overlay_color', colorfield.fields.ColorField(default='#FFFFFF00', max_length=18)),
                ('bg_overlay_check', models.BooleanField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('talkshit', models.TextField(blank=True, null=True)),
                ('talkshit_md', models.TextField(blank=True, null=True)),
                ('text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='FreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='img/f')),
                ('f_img_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('posi_X', models.IntegerField(default=800)),
                ('posi_Y', models.IntegerField(default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.post')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_img_date', models.DateField(blank=True, null=True)),
                ('b_img', models.ImageField(blank=True, null=True, upload_to='img/b', verbose_name='Blog Image')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.post')),
            ],
        ),
    ]
