# Generated by Django 3.1.3 on 2021-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchcategory',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='s_cover',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
