# Generated by Django 3.1.3 on 2021-02-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='b_img_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bg_color_a',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bg_overlay_check',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bg_overlay_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_color',
        ),
    ]
