# Generated by Django 3.1.3 on 2021-11-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0002_auto_20210902_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchbookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('cover', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Sketchbook Category',
                'verbose_name_plural': 'Sketchbook Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'verbose_name': 'Portfolio Category', 'verbose_name_plural': 'Portfolio Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='p_category',
            new_name='portfolio_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_cover',
        ),
        migrations.DeleteModel(
            name='SketchCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='sketchbook_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.sketchbookcategory'),
        ),
    ]
