# Generated by Django 3.2.9 on 2021-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0003_auto_20211121_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchbookcategory',
            name='cover',
        ),
        migrations.AddField(
            model_name='sketchbookcategory',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/sketchbookCover', verbose_name='Blog Image'),
        ),
    ]
