# Generated by Django 3.1.3 on 2021-04-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0003_auto_20210207_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='img/p', verbose_name='Panorama Image')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.portfoliocategory'),
        ),
        migrations.DeleteModel(
            name='FreeImage',
        ),
        migrations.AddField(
            model_name='panoimage',
            name='postpanoimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zblog.post'),
        ),
    ]
