# Generated by Django 3.2.9 on 2021-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0004_auto_20211122_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='b_img_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='b_img_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
