# Generated by Django 3.2.9 on 2021-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0005_auto_20211123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='b_img_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
