# Generated by Django 3.2.9 on 2021-11-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0006_alter_blogimage_b_img_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoimage',
            name='p_img_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='panoimage',
            name='p_img_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
