# Generated by Django 3.2.9 on 2021-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0008_auto_20211123_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='b_img_resize',
            field=models.ImageField(blank=True, null=True, upload_to='img/b/r', verbose_name='Blog Image'),
        ),
    ]
