# Generated by Django 3.2.9 on 2021-11-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0009_blogimage_b_img_resize'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
