# Generated by Django 3.2.9 on 2021-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0010_portfoliocategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='b_img_description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='b_img_paragraph',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
