# Generated by Django 3.2.9 on 2021-11-26 17:55

from django.db import migrations, models
import zblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0011_auto_20211126_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='b_img',
            field=models.ImageField(blank=True, null=True, storage=zblog.models.MediaFileSystemStorage, upload_to='img/b', verbose_name='Blog Image'),
        ),
    ]
