# Generated by Django 3.2.9 on 2021-11-27 22:57

from django.db import migrations, models
import django.db.models.deletion
import zblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0012_auto_20211126_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='b_img_resize',
            field=models.ImageField(blank=True, null=True, storage=zblog.models.MediaFileSystemStorage, upload_to='img/b/r', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='postimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zblog.post'),
        ),
    ]
